# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://benreyn.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Ben Reynolds"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Benjamin Reynolds
author-bio: false  # change to false to hide
author-image: 11561578.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false # https://twitter.com/
facebook: false # https://facebook.com/
instagram: false # https://instagram.com/
github: https://github.com/benreyn
linkedin: https://www.linkedin.com/in/benjamin-reynolds-78147bb8/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
